### ISSUE TITLE
Stuck on 'Syncing...'

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#121]
Floccus can get stuck when the browser is closed while an account is being synced.

**Comment by e-alfred** [comment]
I can confirm this problem. It happens only sometimes though.

**Comment by akidburn** [comment]
Confirmed. Though only in Chrome for me so far, and if its stuck I have to delete the account and add it again.

**Comment by akidburn** [comment]
@marcelklehr Fixed in 2.2.8

**Comment by marcelklehr** [comment]
@akidburn Are you sure? That's quite unlikely. I didn't set out to fix this in v2.2.8 :thinking:

**Comment by skewty** [comment]
FYI, for those following this issue; this is still an issue in beta 5

**Comment by marcelklehr** [comment]
Gonna be fixed in the next beta. :)

**Comment by spupuz** [comment]
i still have that problem with webdav in owncloud never sync

**Comment by marcelklehr** [comment]
@spupuz Hi! I'm happy to troubleshoot! Could you please open a new issue? This one is three years old :)
