### ISSUE TITLE
Chrome bookmarks toolbar: Can't move top level folder to a subfolder (toFolder not defined)

### ISSUE THREAD

**Issue by Larx** [marcelklehr/floccus#181]
### Steps to reproduce

1. Move any folder from the top level of the bookmarks toolbar into another top-level folder of the bookmarks toolbar.
2. Sync

### Expected outcome

Sync ;-)

### Actual outcome

Sync fails with the info "toFolder not defined"
Moving the folder back to the top level of the toolbar cures the problem.

**Comment by marcelklehr** [comment]
Thanks for reporting this! Should be fixed in v3.0.10 :)

**Comment by Larx** [comment]
If I rearrange my bookmarks and delete (sub)folders, I still get this error.

**Comment by marcelklehr** [comment]
Would you be amendable to sending me an excerpt of the debug log of when this occurred?

**Comment by Larx** [comment]
I try to reproduce it right now, but the error did not reappear. I had it all the time a few days ago, now it's gone, grrrr.

**Comment by Larx** [comment]
OK, now the error keeps reappearing, and always: E.g. "title not defined" if moving a subsubfolder to a subfolder or "toFolder not defined" when moving the other way round. When reordering the folders to the original state, everything works again. Moving bookmarks does not cause problems, only folders. And I'm talking of the bookmarks bar in a Chrome-based browser, I don't use any other bookmarks folder structure.

The logfile does not contain any hint that an error occurred at all?!?!

**Comment by Larx** [comment]
In fact I was running 3.0.8. I don't really understand why, as I had used 3.0.10 before when you first fixed this bug (and why there was no update notifcation or so). Anyway, sorry for the noise.

**Comment by marcelklehr** [comment]
No problem, I'm glad we figured it out :)

**Comment by marcelklehr** [comment]
There are no update notifications in floccus at the moment, because Chrome and Firefox automatically update addons.
