### ISSUE TITLE
Floccus is not syncing bookmarks folder 

### ISSUE THREAD

**Issue by fazlerabbi37** [marcelklehr/floccus#193]
### Software versions

* Browser: Google Chrome 70.0.3538.102
* Nextcloud: 14.0.3
* Nextcloud Bookmarks app: 0.14.2
* Floccus: 3.1.2

### Steps to reproduce

1. Add a new account in floccus
2. Click Sync Now
3. Wait for sync to finish.
4. Open NC Bookmark app

### Expected outcome

Bookmarks should be sync with the same folder structure as they are in Google Chrome. 

### Actual outcome

Bookmarks are synced with folder path tag and no folder is created.

**Comment by kevinsarsen** [comment]
Would love to see this added as well. It appears folder support in the Nextcloud Bookmarks app is fairly new so my guess is Floccus just needs to be brought up to date. Hoping this happens soon.

**Comment by fazlerabbi37** [comment]
@kevinsarsen On NC Bookmark, folder support was introduced at v0.14.0 and after a few minor fix at v0.14.2 (released 2 days ago) it works as expected. As per Floccus release note it supports bookmark sync from v3.1.0. But as I described above it is not working as expected and must be a bug.

**Comment by fazlerabbi37** [comment]
@marcelklehr so what are you saying that from the three account options: 
 - Nextcloud Bookmarks (v0.14+)
 - Nextcloud Bookmarks (legacy)
 - XBEL in WebDAV
We need to choose Nextcloud Bookmarks (v0.14+) to get the benefits of folder sync. Well, in that case I already used the Nextcloud Bookmarks (v0.14+) option to sign in yet the problem happened.

**Comment by marcelklehr** [comment]
ooh. I see. The v0.14 option still referenced the old adapter. Fixed now. Thanks for the heads-up!

**Comment by kevinsarsen** [comment]
Well, it worked once for me, but I haven't been able to get my folders to be created since. And the one time it did create the folder structure of my bookmarks, the folders were empty. Am using Nextcloud Bookmarks (v0.14+) and the latest extension version on Vivaldi.

**Comment by fazlerabbi37** [comment]
@marcelklehr can you please re-open the issue? I tested it again with Floccus version 3.1.5 and the issue still exist.

**Comment by marcelklehr** [comment]
@fazlerabbi37 It appears you are still using the legacy adapter. Could you delete the account and create the 0.14+ account again?

@kevinsarsen Mmmh, this is weird. Could you provide me with the debug log?

**Comment by marcelklehr** [comment]
Ah, the default setting was the problem. If you re-select the v0.14 adapter and then create the account it works. I'll release a fix shortly.

**Comment by kevinsarsen** [comment]
Just tried again, starting from scratch and it worked perfectly. Thank you!
