### ISSUE TITLE
AccountSettings doesn't save data (in some cases?)

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/floccus#557]

**Comment by wohali** [comment]
Note that on Linux 68esr as in #554 I can't save an account at all still, not even in a new tab. It always stays as bob@example.com.

**Comment by marcelklehr** [comment]
That's bad :scream_cat: Is there anything going on in the js console?

**Comment by wohali** [comment]
Logs:

```
2020-06-07T15:48:35.900Z Starting sync process for account bob@example.org
2020-06-07T15:48:35.900Z Starting sync process for account bob@example.org
2020-06-07T15:48:36.300Z Using normal strategy
2020-06-07T15:48:35.900Z Starting sync process for account bob@example.org
2020-06-07T15:48:36.300Z Using normal strategy
2020-06-07T15:48:36.600Z Fetching bookmarks
2020-06-07T15:48:36.600Z Syncing failed with E019: HTTP status 404. Failed GET request. Check your server configuration and log.
2020-06-07T15:48:35.900Z Starting sync process for account bob@example.org
2020-06-07T15:48:36.300Z Using normal strategy
2020-06-07T15:48:36.600Z Fetching bookmarks
2020-06-07T15:48:36.600Z Syncing failed with E019: HTTP status 404. Failed GET request. Check your server configuration and log.
```

Console:
```
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. materialdesignicons.min.css:1:682
Expected ‘none’, URL, or filter function but found ‘FlipH’.  Error in parsing value for ‘filter’.  Declaration dropped. materialdesignicons.min.css:1:222932
Expected ‘none’, URL, or filter function but found ‘FlipV’.  Error in parsing value for ‘filter’.  Declaration dropped. materialdesignicons.min.css:1:223033
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. options.html:1:51880
Error in parsing value for ‘border-style’.  Declaration dropped. options.html:1:53259
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. options.html:1:53647
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. options.html:1:53679
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. options.html:1:65682
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. options.html:1:65865
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. options.html:8:143
Error in parsing value for ‘border-style’.  Declaration dropped. options.html:8:1472
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. options.html:8:1860
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector. options.html:8:1892
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. options.html:8:13491
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. options.html:8:13671
Unknown property ‘contain’.  Declaration dropped. options.html:8:168895
Unknown property ‘contain’.  Declaration dropped. options.html:8:171277
Unknown property ‘user-select’.  Declaration dropped. options.html:8:175858
Error in parsing value for ‘max-width’.  Declaration dropped. options.html:8:178146
Unknown property ‘contain’.  Declaration dropped. options.html:8:181428
Unknown property ‘user-select’.  Declaration dropped. options.html:8:184071
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:189797
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:189945
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:192193
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:192337
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. options.html:8:193842
Unknown property ‘user-select’.  Declaration dropped. options.html:8:194496
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:208260
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:208339
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:211617
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:211742
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:212460
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. options.html:8:212586
Unknown property ‘user-select’.  Declaration dropped. options.html:8:213625
Unknown property ‘user-select’.  Declaration dropped. options.html:8:221088
Unknown property ‘user-select’.  Declaration dropped. options.html:8:224580
Unknown property ‘user-select’.  Declaration dropped. options.html:8:226540
Unknown property ‘user-select’.  Declaration dropped. options.html:8:237801
Unknown property ‘user-select’.  Declaration dropped. options.html:8:238448
Unknown property ‘user-select’.  Declaration dropped. options.html:8:238705
Error in parsing value for ‘margin-right’.  Declaration dropped. options.html:8:238922
Unknown property ‘contain’.  Declaration dropped. options.html:8:240240
Unknown property ‘contain’.  Declaration dropped. options.html:8:240640
Unknown property ‘user-select’.  Declaration dropped. options.html:8:256341
Unknown property ‘user-select’.  Declaration dropped. options.html:8:256729
Unknown property ‘user-select’.  Declaration dropped. options.html:8:256988
Unknown property ‘user-select’.  Declaration dropped. options.html:8:257278
Unknown property ‘user-select’.  Declaration dropped. options.html:8:260551
Unknown property ‘user-select’.  Declaration dropped. options.html:8:261142
Unknown property ‘user-select’.  Declaration dropped. options.html:8:264541
Unknown property ‘user-select’.  Declaration dropped. options.html:8:269140
Unknown property ‘user-select’.  Declaration dropped. options.html:8:269663
Unknown property ‘user-select’.  Declaration dropped. options.html:8:269808
Unknown property ‘contain’.  Declaration dropped. options.html:8:271965
Unknown property ‘contain’.  Declaration dropped. options.html:8:272736
Unknown property ‘contain’.  Declaration dropped. options.html:8:273663
Unknown property ‘user-select’.  Declaration dropped. options.html:8:276252
Unknown property ‘user-select’.  Declaration dropped. options.html:8:276808
Unknown property ‘user-select’.  Declaration dropped. options.html:8:277830
Unknown property ‘user-select’.  Declaration dropped. options.html:8:278261
Unknown property ‘user-select’.  Declaration dropped. options.html:8:282493
Unknown property ‘user-select’.  Declaration dropped. options.html:8:285947
Unknown property ‘user-select’.  Declaration dropped. options.html:8:290139
Unknown property ‘contain’.  Declaration dropped. options.html:8:292005
Unknown property ‘user-select’.  Declaration dropped. options.html:8:295051
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:8:298559
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:8:298950
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:8:300175
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:8:300563
Unknown property ‘user-select’.  Declaration dropped. options.html:8:302998
Unknown property ‘contain’.  Declaration dropped. options.html:8:325766
Unknown property ‘contain’.  Declaration dropped. options.html:8:332955
Unknown property ‘user-select’.  Declaration dropped. options.html:8:334975
Unknown pseudo-class or pseudo-element ‘first-child’.  Ruleset ignored due to bad selector. options.html:8:343312
Unknown property ‘user-select’.  Declaration dropped. options.html:8:365644
Unknown property ‘user-select’.  Declaration dropped. options.html:8:390596
Unknown property ‘user-select’.  Declaration dropped. options.html:8:392014
Unknown property ‘user-select’.  Declaration dropped. options.html:8:398179
Unknown property ‘user-select’.  Declaration dropped. options.html:8:399492
Unknown property ‘user-select’.  Declaration dropped. options.html:8:399746
Unknown property ‘user-select’.  Declaration dropped. options.html:1:2338
Error in parsing value for ‘max-width’.  Declaration dropped. options.html:1:4698
Unknown property ‘contain’.  Declaration dropped. options.html:1:166
Unknown property ‘user-select’.  Declaration dropped. options.html:1:610
Unknown property ‘user-select’.  Declaration dropped. options.html:1:3020
Unknown property ‘user-select’.  Declaration dropped. options.html:1:936
Unknown property ‘user-select’.  Declaration dropped. options.html:1:1391
Unknown property ‘user-select’.  Declaration dropped. options.html:1:1468
Unknown property ‘user-select’.  Declaration dropped. options.html:1:1398
Unknown property ‘user-select’.  Declaration dropped. options.html:1:423
Unknown property ‘user-select’.  Declaration dropped. options.html:1:1038
Unknown property ‘user-select’.  Declaration dropped. options.html:1:1968
Unknown property ‘user-select’.  Declaration dropped. options.html:1:2306
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. options.html:1:4439
Unknown property ‘user-select’.  Declaration dropped. options.html:1:5027
Unknown property ‘user-select’.  Declaration dropped. options.html:1:3729
Unknown property ‘user-select’.  Declaration dropped. options.html:1:4989
Unknown property ‘user-select’.  Declaration dropped. options.html:1:5175
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:1:1365
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:1:1635
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:1:3019
Unknown pseudo-class or pseudo-element ‘hover--active’.  Ruleset ignored due to bad selector. options.html:1:3287
Unknown property ‘user-select’.  Declaration dropped. options.html:1:5693
Error in parsing value for ‘height’.  Declaration dropped. options.html
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). options.js:7:115884
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://7c344d82-23e5-4d96-abd2-aacabb2bb1cc/lib/materialdesignicons.min.css
Source Map URL: materialdesignicons.css.map
Error in parsing value for ‘max-width’.  Declaration dropped. options.html
```

**Comment by marcelklehr** [comment]
Thank you. Unfortunately, the logs show nothing interesting going on.

However, I have fixed the incarnation of the bug that I could replicate. Can you try out the attached build to see if this fixes things for you as well?

[floccus-build-test.zip](https://github.com/marcelklehr/floccus/files/4742375/floccus-build-test.zip)

## How to install

### Chrome (separate testing installation)
* Create a new folder
* Unzip the zip file there
* In chrome go to `chrome://extensions/`
* Enable developer mode
* Click `Load unpacked extension` and select the folder you created

### Firefox (separate testing installation; cannot upgrade)
* Unzip the zip file in a new folder
* In firefox go to `about:debugging`
* Click `Load tempoprary addon` and select the manifest file in the folder you created

**Comment by wohali** [comment]
404 on your test build link :sob:

**Comment by marcelklehr** [comment]
hah, haunted by 404s :sweat_smile:

**Comment by marcelklehr** [comment]
It should work now.

**Comment by wohali** [comment]
:joy_cat: Yay! That's *finally* fixed it.

I am still having #482 though, so floccus is still broken on Linux for me.
