### ISSUE TITLE
2 Errors E020: Could not parse server response. AND Trying to insert an already existing item into OrderTracker

### ISSUE THREAD

**Issue by tchap2** [marcelklehr/floccus#641]
**Describe the bug**

When I sync Firefox toolbar with /xyz folder on server, I get error message:

"E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data "

I DELETED account and folder from Nextcloud (to flush ALL changes from server), then added account again but this time as follows:

When I sync Firefox bookmarks (ROOT) with /xyz folder on server, I get error message: Trying to insert an already existing item into OrderTracker: bookmark:1nEHKoutQMqH

**To Reproduce**
1. Go to 'add new account, map local folder "Bookmarks Toolbar" to server folder "/XYZ".'
2. Click on '.SYNC NOW'
3. Scroll down to '....' - NOT APPLICABLE
E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected character at line 1 column 1 of the JSON data 

**To Reproduce - ACTION 2**
1. Go to 'add new account, map local ROOT (!!!) folder "Untitled Folder" to server folder "/XYZ".'
2. Click on '.SYNC NOW'
3. Scroll down to '....' - NOT APPLICABLE
Trying to insert an already existing item into OrderTracker: bookmark:1nEHKoutQMqH

**Expected behavior**
Completed sync without errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser - firefox
 - Browser Version - 79.0
 - Floccus version: 4.2.6
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: ---
 - Nextcloud version: 17.0.1
 - Bookmarks app version: ---

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

**Comment by marcelklehr** [comment]
I'm not sure what happened on the first try, but the second try is probably an incarnation of #598 which will be fixed with the next release. I'll leave this open till then.

**Comment by marcelklehr** [comment]
@tchap2 Do you still experience this issue?

**Comment by marcelklehr** [comment]
(The first error could actually be due to nextcloud brute force protection kicking in)

**Comment by CouldBeThis** [comment]
I am not sure if this is directly helpful but I am going to post in case it's useful to someone else who is a bit dense like me and searches for it. 

Also got e020 on new install. Content of the logs was basically

```
Starting sync process for account nextcloud@host.com
Using normal strategy
Fetching bookmarks
Syncing failed with E020: Could not parse server response. Is the bookmarks app installed on your server?
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

The solution: 

In the field labeled `nextcloud URL` you put the URL of the nextcloud, *not* the webDAV URL

`https://nextcloud.host.com/` not `https://nextcloud.host.com/remote.php/dav/files/user/`

floccus is clever enough to figure out the rest.

**Comment by marcelklehr** [comment]
Thanks for all your feedback, folks! I'm currently working on a new iteration of the sync algorithm that should fix this: #651

**Comment by marcelklehr** [comment]
I've since rewritten the sync algorithm to avoid this kind of problems. Head over to https://github.com/marcelklehr/floccus/issues/666 if you'd like to help test the new version.

**Comment by fredbcode** [comment]
This bug still present on 4.4.6, tested with url (not webdav link) nextcloud 20.0.1, Firefox 82.0.2
`
E020: Impossible de lire la réponse du serveur. L'application de marque-pages est elle installée sur votre serveur? JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by fredbcode** [comment]
Right now I also note that sub directories are duplicated at each synchronization

![image](https://user-images.githubusercontent.com/5287473/98841206-11371580-2448-11eb-9ace-1668e0fff42a.png)

**Comment by tchap2** [comment]
> @tchap2 Do you still experience this issue?

Hello, YES! The issue is still there.
After not using Floccus for ~6 months, I again downloaded the addon to Firefox, set up the account (to root folder), and I again received error (from debug logs) - this is the only error:

_2020-11-13T16:17:27.039Z { [Error: 1 errors]
  list: 
   [ [Error: E020: Could not parse server response. Is the bookmarks app installed on your server?
     JSON.parse: unexpected character at line 1 column 1 of the JSON data] ] }
2020-11-13T16:17:27.040Z [Error: E020: Could not parse server response. Is the bookmarks app installed on your server?
JSON.parse: unexpected character at line 1 column 1 of the JSON data]
2020-11-13T16:17:27.041Z Syncing failed with E020: Could not parse server response. Is the bookmarks app installed on your server?
JSON.parse: unexpected character at line 1 column 1 of the JSON data_

I do not understand where this JSON file is located (firefox browser, one of my bookmarks http address, nexcloud server?????) What is the unexpected character?

**Comment by tchap2** [comment]
> I am not sure if this is directly helpful but I am going to post in case it's useful to someone else who is a bit dense like me and searches for it.
> 
> Also got e020 on new install. Content of the logs was basically
> 
> ```
> Starting sync process for account nextcloud@host.com
> Using normal strategy
> Fetching bookmarks
> Syncing failed with E020: Could not parse server response. Is the bookmarks app installed on your server?
> JSON.parse: unexpected character at line 1 column 1 of the JSON data
> ```
> 
> The solution:
> 
> In the field labeled `nextcloud URL` you put the URL of the nextcloud, _not_ the webDAV URL
> 
> `https://nextcloud.host.com/` not `https://nextcloud.host.com/remote.php/dav/files/user/`
> 
> floccus is clever enough to figure out the rest.

This is exactly what was done. This does not change the issue nor this ticket.

**Comment by marcohald** [comment]
I also have this issue with Nextcloud 20.0.2 , Bookmarks 4.0.5 and floccus 4.4.6

> 2020-11-23T09:25:12.003Z Syncing failed with E020: Antwort des Servers konnte nicht gelesen werden. Ist die Bookmarks App auf Ihrem Server installiert?
> JSON.parse: unexpected character at line 1 column 1 of the JSON data

I tried this https://github.com/marcelklehr/floccus/issues/666#issuecomment-704172666
>  - Deduplicate shared bookmark folders
>      - Removed 0 duplicate shares
>  - Remove superfluous shared bookmark folders
>      - Removed 0 superfluous shares
>  - Remove orphaned bookmark shares
>      - Removed 0 orphaned shares
>      - Removed 0 orphaned public links
>  - Remove orphaned bookmark tree items
>      - Removed 228 orphaned bookmarks entries
>      - Removed 0 orphaned folders entries
>      - Removed 42 orphaned children entries
>      - Removed 0 orphaned bookmark folders
>      - Removed 0 orphaned bookmarks
>  - Update bookmark group shares
>      - Removed 0 users and added 0 users to 0 groups
>      - Removed 0 shares

But still receive this error.

**Comment by marcohald** [comment]
I debugged it via about:debugging and saw that a bad response from our Reverse Proxy was cached fro the URL index.php/apps/bookmarks/public/rest/v2/folder?root=-1&layers=0
I rgith clicked my Nextcloud Site on the Firefox history and deleted it via forget this site.
Now it works again.

**Comment by fredbcode** [comment]
No reverse here and floccus is unfortunately unusable in my case 
Do you have directories in your bookmarks ? Maybe ( https://github.com/marcelklehr/floccus/issues/641#issuecomment-725541654 ) is a glue about this issue ?

**Comment by pcwilcox** [comment]
I was having this issue as well, following @marcohald 's comment I deleted the site from my firefox history, then removed the account from floccus, then recreated it. When I first recreated it I used the 'nextcloud flow' method, and this didn't work. I went into my nextcloud settings and created a new app password for floccus, put this password into the account settings in floccus, and now it's syncing.

**Comment by marcelklehr** [comment]
I'm sorry for the delay. I've just released v4.4.7 for firefox with a lot of new fixes, hopefully this will some of your issues. A few issues remain, but I'm confident I'll be able to tackle those soon.

**Comment by KaratekHD** [comment]
Same happens here:
Nextcloud Bookmarks Version: 4.0.5

I get this output in my Nextcloud log:
```
Exception: Argument 1 passed to OCA\Bookmarks\Db\TreeMapper::getSubFolders() must be of the type int, null given, called in /srv/www/htdocs/nextcloud/apps/bookmarks/lib/Controller/FoldersController.php on line 444

    /srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "getFolders")

    /srv/www/htdocs/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Bookma ... r", "getFolders", OC\AppFramew ... {}, { action: nu ... "})

    /srv/www/htdocs/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/bookm ... r")

    /srv/www/htdocs/nextcloud/index.php - line 37:

    OC::handleRequest()

Verursacht durchTypeError: Argument 1 passed to OCA\Bookmarks\Db\TreeMapper::getSubFolders() must be of the type int, null given, called in /srv/www/htdocs/nextcloud/apps/bookmarks/lib/Controller/FoldersController.php on line 444

    /srv/www/htdocs/nextcloud/apps/bookmarks/lib/Controller/FoldersController.php - line 444:

    OCA\Bookmarks\Db\TreeMapper->getSubFolders(null, -1)

    /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Bookmarks\Controller\FoldersController->getFolders(-1, -1)

    /srv/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "getFolders")

    /srv/www/htdocs/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "getFolders")

    /srv/www/htdocs/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Bookma ... r", "getFolders", OC\AppFramew ... {}, { action: nu ... "})

    /srv/www/htdocs/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/bookm ... r")

    /srv/www/htdocs/nextcloud/index.php - line 37:

    OC::handleRequest()
```
I hope this helps resolving  this issue.

**Comment by wu-lee** [comment]
I'm seeing this error:

E020: Could not parse server response. Is the bookmarks app installed on your server? JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

On the server logs, I see:

```
  Error    PHP                Allowed memory size of 2021-01-16T15:35:58+00:00 
                              536870912 bytes                                  
                              exhausted (tried to                              
                              allocate 268435464                               
                              bytes) at                                        
                              /var/www/html/apps/bookmarks/lib/Db/BookmarkWithTagsAndParent.php#48  
```

I could try and increase the PHP limit, but I wonder if this is sensible: does syncing bookmarks really need 500MB?

**Comment by marcelklehr** [comment]
@KaratekHD You likely have two root folders for that user in the database. The fix would be to remove the one that doesn't contain any other folders.

Short guide for that:

The table `oc_bookmarks_root_folders` maps a user_id to a folder_id. In `oc_bookmarks_tree` you can find entries that have that folder_id as their parent_folder to see what is in that root folder. You can drop the entry in oc_bookmarks_root_folders that has no children in oc_bookmarks_tree.

**Comment by marcelklehr** [comment]
@wu-lee Oof, I have not analyzed the memory footprint of the app so far, but that looks like a bit too much indeed. I'll create a new issue on the bookmarks app to track this, but for now the quick fix would indeed be to increase the memory limit maybe by a hundred or two hundred mb. :S

**Comment by KaratekHD** [comment]
> @KaratekHD You likely have two root folders for that user in the database. The fix would be to remove the one that doesn't contain any other folders.
> 
> Short guide for that:
> 
> The table `oc_bookmarks_root_folders` maps a user_id to a folder_id. In `oc_bookmarks_tree` you can find entries that have that folder_id as their parent_folder to see what is in that root folder. You can drop the entry in oc_bookmarks_root_folders that has no children in oc_bookmarks_tree.

Thank you, this worked!

**Comment by marcelklehr** [comment]
> I'm sorry for the delay. I've just released v4.4.7 for firefox with a lot of new fixes, hopefully this will some of your issues. A few issues remain, but I'm confident I'll be able to tackle those soon. Feedback is appreciated.

v4.4.8 is out now with more fixes. I'm closing this now, feel free to open a new issue if you continue to experience problems.

**Comment by boggle247** [comment]
V4.6.4 Floccus 
Brave Browser 
Pop_os! 20.04 & 20.10
Nextcloud 20.0.8

I get the following error:
`E020: Could not parse server response. Is the bookmarks app installed on your server? Unexpected token < in JSON at position 0`

here is the last bit of my error log:
```
2021-07-01T18:30:43.504Z (nextcloud-folders)ORDERFOLDER { id: 931,
  order: 
   [ { type: 'bookmark', id: '3758;931' },
     { type: 'bookmark', id: '3759;931' },
     { type: 'bookmark', id: '3760;931' },
     { type: 'bookmark', id: '3761;931' },
     { type: 'bookmark', id: '3762;931' },
     { type: 'bookmark', id: '3763;931' },
     { type: 'bookmark', id: '3764;931' },
     { type: 'folder', id: 949 },
     { type: 'folder', id: 950 } ] }
2021-07-01T18:30:44.972Z { [Error: 1 errors] list: [ { [Error: 1 errors] list: [Object] } ] }
2021-07-01T18:30:44.973Z { [Error: 1 errors]
  list: 
   [ [Error: E020: Could not parse server response. Is the bookmarks app installed on your server?
     Unexpected token < in JSON at position 0] ] }
2021-07-01T18:30:44.973Z [Error: E020: Could not parse server response. Is the bookmarks app installed on your server?
Unexpected token < in JSON at position 0]
2021-07-01T18:30:44.974Z Syncing failed with E020: Could not parse server response. Is the bookmarks app installed on your server?
```

I didn't include more because I don't know how to sanitize it of personal info and my bookmarks etc. 

&nbsp;

**Attempted fixes**
* Delete all bookmarks from bookmark app via button in nextcloud web panel. 
* trigger sync from scratch
* reinstallation of floccus app.


Also, my wife has the exact same setup (machine, distro, etc) only difference is that she is a different user on my nextcloud instance. I am the admin user on the server. She has ZERO issues syncing.

**Comment by marcelklehr** [comment]
Hi @boggle247 Could you please open a new issue for this? Also, this may be caused by a server error, so try to go through your nextcloud log for related errors.

**Comment by boggle247** [comment]
@marcelklehr I'm in the matrix room for nextcloud bookmarks trying to resolve the issue. If I find that it is indeed something with floccus, then I'll create a new issue. Otherwise, I'll update this with the nextcloud issue, if that's acceptable.
