### ISSUE TITLE
Bug? "Invalid children order: To many children"

### ISSUE THREAD

**Issue by Grunthos** [marcelklehr/floccus#745]
**Describe the bug**

Sync now results in:
```Nextcloud API error: {"status":"error","data":"invalid children order: To many children"} ```

**To Reproduce**

Was working fine, now any sync produces this error.

**Expected behavior**
Normal sync?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefix
 - Browser Version: 83.0 
 - Floccus version: 4.4.6
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Lunuz
 - Nextcloud version: 19.0.4
 - Bookmarks app version: 3.4.9

**Debug log**
Tail of log is:

```
2020-12-15T10:44:18.171Z { reorderings: [] }
2020-12-15T10:44:21.066Z [Error: Nextcloud API error: 
{"status":"error","data":"invalid children order: To many children"}]
2020-12-15T10:44:21.066Z Syncing failed with Nextcloud API error: 
{"status":"error","data":"invalid children order: To many children"}
```
I *do* have a lot of bookmarks.

**Comment by Grunthos** [comment]
A "dangerous" sync fixed the problem...

**Comment by marcelklehr** [comment]
The latest patch releases in the v4.4.x series fixed this problem. Thank you for your feedback. Feel free to open a new issue if you continue to experience problems.

**Comment by marcohald** [comment]
Hi.

I also have the error invalid children order: To many children.
My Firefox Version is 85.0b9 and Floccus is on Version 4.4.8
I debugged Floccus in about:debugging the Last Request on a sync Windows does get an error Code 400 back from the Server.

![grafik](https://user-images.githubusercontent.com/10107699/105824636-e9733a80-5fbe-11eb-8cdf-4fee1cf41881.png)
This is the Content send on the Request:
`{"data":[{"id":"8053","type":"folder"},{"id":"8056","type":"folder"},{"id":"8055","type":"folder"},{"id":"8057","type":"folder"},{"id":"8054","type":"folder"},{"id":"8052","type":"folder"},{"id":"8060","type":"folder"},{"id":"8058","type":"folder"},{"id":"8059","type":"folder"},{"id":"8061","type":"folder"},{"id":"8062","type":"folder"},{"id":"8986","type":"bookmark"},{"id":"8606","type":"bookmark"},{"id":"8602","type":"bookmark"},{"id":"8600","type":"bookmark"},{"id":"8601","type":"bookmark"},{"id":"8603","type":"bookmark"},{"id":"8888","type":"bookmark"},{"id":"8607","type":"bookmark"},{"id":"8610","type":"bookmark"},{"id":"8608","type":"bookmark"},{"id":"8604","type":"bookmark"},{"id":"8611","type":"bookmark"},{"id":"8605","type":"bookmark"},{"id":"8609","type":"bookmark"},{"id":"8613","type":"bookmark"},{"id":"8614","type":"bookmark"},{"id":"8618","type":"bookmark"},{"id":"8615","type":"bookmark"},{"id":"8617","type":"bookmark"},{"id":"8612","type":"bookmark"},{"id":"8616","type":"bookmark"},{"id":"8626","type":"bookmark"},{"id":"8620","type":"bookmark"},{"id":"8619","type":"bookmark"},{"id":"8621","type":"bookmark"},{"id":"8622","type":"bookmark"},{"id":"8630","type":"bookmark"},{"id":"8623","type":"bookmark"},{"id":"8632","type":"bookmark"},{"id":"8624","type":"bookmark"},{"id":"8631","type":"bookmark"},{"id":"8627","type":"bookmark"},{"id":"8625","type":"bookmark"},{"id":"8633","type":"bookmark"},{"id":"8628","type":"bookmark"},{"id":"8629","type":"bookmark"},{"id":"8635","type":"bookmark"},{"id":"8641","type":"bookmark"},{"id":"8639","type":"bookmark"},{"id":"8638","type":"bookmark"},{"id":"8637","type":"bookmark"},{"id":"8634","type":"bookmark"},{"id":"8643","type":"bookmark"},{"id":"8640","type":"bookmark"},{"id":"8636","type":"bookmark"},{"id":"8647","type":"bookmark"},{"id":"8652","type":"bookmark"},{"id":"8642","type":"bookmark"},{"id":"8649","type":"bookmark"},{"id":"8659","type":"bookmark"},{"id":"8648","type":"bookmark"},{"id":"8064","type":"folder"},{"id":"8651","type":"bookmark"},{"id":"8650","type":"bookmark"},{"id":"8653","type":"bookmark"},{"id":"8657","type":"bookmark"},{"id":"8658","type":"bookmark"},{"id":"8660","type":"bookmark"},{"id":"8656","type":"bookmark"},{"id":"8654","type":"bookmark"},{"id":"8655","type":"bookmark"},{"id":"8661","type":"bookmark"},{"id":"8663","type":"bookmark"},{"id":"8662","type":"bookmark"},{"id":"8676","type":"bookmark"},{"id":"8664","type":"bookmark"},{"id":"8675","type":"bookmark"},{"id":"8665","type":"bookmark"},{"id":"8741","type":"bookmark"},{"id":"8677","type":"bookmark"},{"id":"8065","type":"folder"},{"id":"8674","type":"bookmark"},{"id":"8680","type":"bookmark"},{"id":"8678","type":"bookmark"},{"id":"8747","type":"bookmark"},{"id":"8686","type":"bookmark"},{"id":"8717","type":"bookmark"},{"id":"8066","type":"folder"},{"id":"8067","type":"folder"},{"id":"8068","type":"folder"},{"id":"8071","type":"folder"},{"id":"8069","type":"folder"},{"id":"8070","type":"folder"},{"id":"8072","type":"folder"},{"id":"8073","type":"folder"},{"id":"8744","type":"bookmark"},{"id":"8886","type":"bookmark"},{"id":"8815","type":"bookmark"},{"id":"8076","type":"folder"},{"id":"8075","type":"folder"},{"id":"8074","type":"folder"},{"id":"8077","type":"folder"},{"id":"8078","type":"folder"},{"id":"8079","type":"folder"},{"id":"8381","type":"folder"},{"id":"8082","type":"folder"},{"id":"8081","type":"folder"},{"id":"8084","type":"folder"},{"id":"8085","type":"folder"},{"id":"8083","type":"folder"},{"id":"8086","type":"folder"},{"id":"8838","type":"bookmark"},{"id":"8836","type":"bookmark"},{"id":"8837","type":"bookmark"},{"id":"8839","type":"bookmark"},{"id":"8841","type":"bookmark"},{"id":"8840","type":"bookmark"},{"id":"8843","type":"bookmark"},{"id":"8844","type":"bookmark"},{"id":"8842","type":"bookmark"},{"id":"8868","type":"bookmark"},{"id":"8846","type":"bookmark"},{"id":"8848","type":"bookmark"},{"id":"8847","type":"bookmark"},{"id":"8845","type":"bookmark"},{"id":"8849","type":"bookmark"},{"id":"8850","type":"bookmark"},{"id":"8851","type":"bookmark"},{"id":"8855","type":"bookmark"},{"id":"8852","type":"bookmark"},{"id":"8853","type":"bookmark"},{"id":"8854","type":"bookmark"},{"id":"8080","type":"folder"},{"id":"8088","type":"folder"},{"id":"8089","type":"folder"},{"id":"8090","type":"folder"},{"id":"8091","type":"folder"},{"id":"8080","type":"folder"},{"id":"8874","type":"bookmark"},{"id":"8870","type":"bookmark"},{"id":"8873","type":"bookmark"},{"id":"8869","type":"bookmark"},{"id":"8871","type":"bookmark"},{"id":"8872","type":"bookmark"},{"id":"8878","type":"bookmark"},{"id":"8875","type":"bookmark"},{"id":"8879","type":"bookmark"},{"id":"8876","type":"bookmark"},{"id":"8885","type":"bookmark"},{"id":"8877","type":"bookmark"},{"id":"8534","type":"bookmark"},{"id":"8093","type":"folder"},{"id":"8880","type":"bookmark"},{"id":"8094","type":"folder"},{"id":"8915","type":"bookmark"},{"id":"8988","type":"bookmark"}]}`

**Comment by marcohald** [comment]
I just noticed that i replied to a closed issue.
@marcelklehr  Can you reopen the issue or should I create a new one ?

**Comment by marcelklehr** [comment]
I've published new versions of both floccus and bookmarks.

**Comment by marcohald** [comment]
I upgraded both.
I'm now on Version 4.08 for the Bookmarks App and 4.4.9 for Floccus.
The issue is still the same. Even the JSON send to the Server is exactly the same.

**Comment by marcelklehr** [comment]
Alright, I see the problem now, there's one folder showing up twice in the ordering.

**Comment by marcelklehr** [comment]
Can you try again with the latest version?

**Comment by marcohald** [comment]
It is now working.

**Comment by wohali** [comment]
I can confirm this has **finally** fixed my issues to date, in conjunction with the fixes over in #716.

Thank you @marcelklehr for all your hard work!

**Comment by marcelklehr** [comment]
Yaaay, I'm so happy it works for you now, @wohali!
