### ISSUE TITLE
invalid children order: A child is missing: bookmark:2325

### ISSUE THREAD

**Issue by thd6n75** [marcelklehr/floccus#800]
**Describe the bug**
When syncing with Nextcloud, floccus fails with the message:

```
Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: bookmark:2325"}
```

Similar to https://github.com/marcelklehr/floccus/issues/705 .  When this happens, Floccus consumes a lot of CPU.

**To Reproduce**
1.  Sync

**Expected behavior**

Successful sync

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium
 - Browser Version Version 89.0.4385.0 (Developer Build) Ubuntu 18.04 (64-bit)
 - Floccus version: 4.4.8 (released yesterday, but I think the problem pre-dates this)
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nextcloud version: 20.0.3
 - Bookmarks app version: 4.0.6 (problem initially occurred I think on 4.0.4 before I updated to 4.0.6)

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [ ] Debug log provided

**Additional context**

This didn't fix the issue:

```
docker exec --user www-data nextcloud php occ maintenance:repair
```

output:

```
 - Deduplicate shared bookmark folders
     - Removed 0 duplicate shares
 - Remove superfluous shared bookmark folders
     - Removed 0 superfluous shares
 - Remove orphaned bookmark shares
     - Removed 0 orphaned shares
     - Removed 0 orphaned public links
 - Remove orphaned bookmark tree items
     - Removed 0 orphaned bookmarks entries
     - Removed 0 orphaned folders entries
     - Removed 0 orphaned children entries
     - Removed 0 orphaned bookmark folders
     - Removed 0 orphaned bookmarks
 - Update bookmark group shares
     - Removed 0 users and added 0 users to 0 groups
     - Removed 0 shares
```

A "sync from scratch" seems to temporarily fix this, but a couple syncs later the problem occurs again persistently.

**Comment by sinesiobittencourt** [comment]
Hi!

I have the same error and so far I have not found a solution.

I hope the community helps.

tks!

**Comment by tradespite** [comment]
Same problem occurred to me today.

It was fixed by updating:
Floccus version: 4.4.8 -> 4.4.9
Bookmarks app version: 4.0.6 -> 4.0.8

**Comment by thd6n75** [comment]
I updated:

Floccus version: 4.4.9
Bookmarks app version: 4.0.8

And I still get this error after a sync from scratch.

**Comment by marcelklehr** [comment]
Can you try again with the latest version?

**Comment by thd6n75** [comment]
I've been running 4.4.10 for a day and it seems to have fixed the issue.  Thanks!
